---
substitutions:
  time_timezone: "Australia/Melbourne"
  time_update_interval: 6h

time:
  - platform: sntp
    id: time_sntp
    timezone: "${time_timezone}"
    update_interval: ${time_update_interval}
